name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx4G -Xss4M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx4G -Xss4M # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: sbt lint

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        scala: [ '2.12.16', '2.13.8', '3.2.2' ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests for Scala ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }}! enableStrictCompile test

  publish:
    runs-on: ubuntu-20.04
    needs: [ lint, test ]
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: sbt publish-all
        env:
          GITHUB_TOKEN: ${{ github.token }}
